name: meshnet_messenger
description: A futuristic, decentralized, peer-to-peer encrypted messaging platform built to work over mesh networks with a focus on privacy, encryption, and immersive experiences.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  sqflite: ^2.2.5
  connectivity_plus: ^3.0.3
  permission_handler: ^10.4.3
  file_picker: ^5.3.1
  uuid: ^3.0.7
  crypto: ^3.0.3
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  vector_math: ^2.1.4
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  url_launcher: ^6.1.12
  sensors_plus: ^2.0.2
  flutter_local_notifications: ^15.1.0+1
  lottie: ^2.6.0
  video_player: ^2.6.0
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.6.14
  rive: ^0.10.3
  flutter_animate: ^4.2.0
  audioplayers: ^3.0.1
  flutter_3d_objects: ^1.0.1
  just_audio: ^0.9.32
  flex_color_scheme: ^7.0.0
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.1
  flutter_spinkit: ^5.2.0
  web_socket_channel: ^2.2.0
  intl: ^0.18.1
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^2.0.0
  rxdart: ^0.27.7
  vibration: ^1.7.6
  camera: ^0.10.5+2
  local_auth: ^2.1.6
  flutter_secure_storage: ^8.0.0
  fluttertoast: ^8.2.2
  image: ^4.0.17
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/avatars/
    
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
        - asset: assets/fonts/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/Exo-Medium.ttf
          weight: 500 